// Phase G — Automatic Crash Detection Simulation
// crashDetectionService.js — Service layer (MVP simulation + future-ready stubs)

// ─────────────────────────────────────────────────────────────────────────────
// SIMULATION (MVP — active)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Simulate a crash detection event.
 * In a future version this will be replaced by real sensor pipeline output.
 *
 * @returns {{
 *   detected: boolean,
 *   confidence: string,
 *   triggerType: string,
 *   severity: string,
 *   message: string,
 *   timestamp: string,
 * }}
 */
export function simulateCrashDetection() {
  return {
    detected: true,
    confidence: "Simulation",
    triggerType: "Crash Detection Simulation",
    severity: "High Risk",
    message: "Possible crash detected through simulation mode.",
    timestamp: new Date().toISOString(),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// EMERGENCY MESSAGE BUILDER (active)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build a shareable emergency alert message.
 *
 * @param {{ lat: number, lng: number } | null} location
 * @param {string} triggerType
 * @returns {string}
 */
export function generateCrashAlertMessage(location, triggerType = "Crash Detection Simulation") {
  const mapsLink = location
    ? `https://maps.google.com/?q=${location.lat},${location.lng}`
    : null;

  const locationLine = mapsLink
    ? `My current location:\n${mapsLink}`
    : "Location: Unable to determine (please contact me directly)";

  return `🚨 Emergency Alert!

A possible crash has been detected by RoadSoS.

${locationLine}

Please contact me or emergency services immediately.
National Emergency: 112
Ambulance: 108

Triggered by: ${triggerType}

Generated by RoadSoS — Road Safety Emergency System.`;
}

// ─────────────────────────────────────────────────────────────────────────────
// FUTURE-READY STUBS
// (Not active in MVP — safe to call, returns descriptive placeholder result)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * [FUTURE] Analyse raw accelerometer data for impact signature.
 *
 * In a production version this would:
 *  - Accept DeviceMotionEvent data (acceleration.x/y/z)
 *  - Check for delta > impact threshold (e.g. >25 m/s²)
 *  - Debounce false positives from road bumps
 *
 * @param {object} sensorData - DeviceMotionEvent sensor readings
 * @returns {{ supported: boolean, impactDetected: boolean, message: string }}
 */
export function analyzeAccelerometerData(sensorData) {
  // Future: replace with real threshold analysis
  void sensorData;
  return {
    supported: false,
    impactDetected: false,
    message:
      "Accelerometer-based detection is planned for future mobile versions. Requires DeviceMotion API permission.",
  };
}

/**
 * [FUTURE] Detect GPS anomaly — sudden location jump inconsistent with normal travel.
 *
 * In a production version this would:
 *  - Compare distance between two recent GPS points vs. time elapsed
 *  - Flag if speed implied by GPS jump is physically impossible
 *  - Or if GPS signal suddenly vanishes (possible tunnel / impact)
 *
 * @param {{ lat: number, lng: number } | null} previousLocation
 * @param {{ lat: number, lng: number } | null} currentLocation
 * @returns {{ anomalyDetected: boolean, reason: string }}
 */
export function detectGPSAnomaly(previousLocation, currentLocation) {
  // Future: haversine distance + time delta check
  void previousLocation;
  void currentLocation;
  return {
    anomalyDetected: false,
    reason: "GPS anomaly detection is a future feature. Requires continuous location stream.",
  };
}

/**
 * [FUTURE] Calculate speed drop magnitude between two readings.
 *
 * In a production version this would trigger a crash alert when
 * speed drops > 30 km/h in under 200ms (indicative of sudden stop).
 *
 * @param {number} previousSpeed  km/h
 * @param {number} currentSpeed   km/h
 * @returns {{ suddenDrop: boolean, dropMagnitude: number }}
 */
export function calculateSpeedDrop(previousSpeed, currentSpeed) {
  // Future: active speed drop detection
  void previousSpeed;
  void currentSpeed;
  return {
    suddenDrop: false,
    dropMagnitude: 0,
  };
}

/**
 * [FUTURE] Request DeviceMotion sensor permission (iOS 13+ requires explicit request).
 *
 * @returns {Promise<"granted" | "denied" | "unsupported">}
 */
export async function requestMotionPermission() {
  if (typeof DeviceMotionEvent === "undefined") {
    return "unsupported";
  }
  if (typeof DeviceMotionEvent.requestPermission === "function") {
    try {
      const result = await DeviceMotionEvent.requestPermission();
      return result === "granted" ? "granted" : "denied";
    } catch {
      return "denied";
    }
  }
  // Android / desktop — no permission API, assume available
  return "granted";
}
